# Generated by Django 5.1.7 on 2025-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychanel', '0005_webinarregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='zoom_webinar_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
