# Generated by Django 5.1.7 on 2025-05-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychanel', '0006_webinar_zoom_webinar_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebinarRegistration',
        ),
    ]
